server:
  port: 16666

logging:
  level: debug

hbaseconf:
  hbase_zk_quorum: "zookeeper-bpshq-0.zookeeper-bpshq.inceptor.svc,zookeeper-bpshq-1.zookeeper-bpshq.inceptor.svc,zookeeper-bpshq-2.zookeeper-bpshq.inceptor.svc"
  zk_znode_parent: "/hyperbase1"
  hbase_zk_property_client_port: "2181"
  db_name: "default"
  table_name: "dwd_suishenma_d_hyperbase"
  decode_num: 18
  principal: "hbase/tos_inceptor@INCEPTOR.TDH"
  authentication: "kerberos"
  keytab_file: "/etc/keytabs/keytab"
  login_user: "hbase/tos_inceptor"