##---
# Source: hbase-health/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hbasehealth-conf
  namespace: 2ca6w9n
  labels:
    app: hbase-health
    chart: hbase-health-1.0.0
    heritage: Tiller
    release: hbasehealth
data:
  application.yml: |-
    server:
      port: 16666

    logging:
      level: error

    hbaseconf:
      hbase_zk_quorum: "zookeeper-p5f7b-0.2ca6w9n.pod,zookeeper-p5f7b-1.2ca6w9n.pod,zookeeper-p5f7b-2.2ca6w9n.pod"
      zk_znode_parent: "/hyperbase1"
      hbase_zk_property_client_port: "2181"
      db_name: "bangongting_shared"
      table_name: "dwd_suishenma_d_hyperbase"
      decode_num: 21
