apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: hbase-health
    chart: hbase-health-1.0.0
    heritage: Tiller
    release: hbasehealth    
  namespace: 2ca6w9n
  name: hbasehealth-monitor
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: web
    path: /prometheus
  jobLabel: component
  namespaceSelector:
    matchNames:
    - 2ca6w9n
  selector:
    matchLabels:
      app: hbase-health

