apiVersion: v1
kind: Service
metadata:
  annotations:
     service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: hbase-health
    chart: hbase-health-1.0.0
    heritage: Tiller
    release: hbasehealth
  name: hbasehealth-svc
  namespace: 2ca6w9n
spec:
  type: NodePort
  ports:
   - port: 16666
     name: web
  selector:
     app: hbase-health
     release: hbasehealth
